---
title: "Graph drawing with netplot"
author: "George G. Vega Yon"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Some features:

1.  Auto-scaling of vertices using sizes relative to the plotting device.
2.  Embedded edge color mixer.
3.  True curved edges drawing.
4.  User-defined edge curvature.
5.  Nicer vertex frame color.
6.  Better use of space filling the plotting device.


```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction

```{r nplot-vs-plot, fig.width=7, fig.height=7, fig.cap="Comparision of default `igraph` vs `netplot` default call. `nplot` fills completely the plotting area, and adjusts vertex size, edge width, and edge arrows' size accordingly to the plotting area and plotting device."}
library(netplot)
library(igraph)


set.seed(225)
x <- sample_smallworld(1, 100, 4, .1)
l <- layout_with_fr(x)

oldpar <- par(mfrow = c(2,2))
plot(x, layout = l)
sna::gplot(as.matrix(as_adj(x)), coord = l)
nplot(x, layout = l)
par(oldpar)
```

# Nodes

```{r node-scaling, fig.width=7, fig.height=7, fig.cap="Modifying `vertex.size.range`: Each figure shows a different parameter for the vertex size range. From left to right, and top down: (a) Has all vertices with the same scale of 2.5%, (b) "}
oldpar <- par(mfrow=c(2,2))
nplot(x, layout = l, vertex.size.range = c(.025, .025))
nplot(x, layout = l, vertex.size.range = c(.01, .025))
nplot(x, layout = l, vertex.size.range = c(.01, .025, 4))
nplot(x, layout = l, vertex.size.range = c(.02, .05, 4))
par(oldpar)
```

```{r node-shapes, fig.width=4, fig.height=4, fig.cap="Number of sides for node drawing."}
nplot(make_ring(5), vertex.shape = 2:6,
      vertex.size.range = c(.1,.1),
      edge.curvature = 0)
```

# Edges

```{r sim-net}
set.seed(12233)

x <- sample_smallworld(1, size = 10, nei = 2, .1)
l <- layout_with_fr(x)
```


```{r edge-color, fig.width=7, fig.height=3, fig.cap="Modifying `edge.color.mix`: Each figure shows a different parameter for the edge color mixer. From left to right, (a) colors the edges as alter, (b) mixes ego and alter's colors, and (c) only uses ego"}
oldpar <- par(mfrow = c(1,3))
nplot(x, layout = l, edge.color.mix = 1, vertex.size.range = c(.05,.1))
nplot(x, layout = l, edge.color.mix = .5, vertex.size.range = c(.05,.1))
nplot(x, layout = l, edge.color.mix = 0, vertex.size.range = c(.05,.1))
par(oldpar)
```

```{r edge-curvature, fig.width=7, fig.height=3, fig.cap="Modifying `edge.curvature`: Each figure shows a different parameter for the edge curvature. From left to right, (a) straight edges, (b) the edge between ego and alter is an arc that measures $\\pi/2$ radians (90 degree), and (c) the edge as an arc between ego and alter that measures $\\pi$ radians (180 degrees)."}
oldpar <- par(mfrow = c(1,3))
nplot(x, layout = l, edge.curvature = 0, vertex.size.range = c(.05,.1))
nplot(x, layout = l, edge.curvature = pi/2, vertex.size.range = c(.05,.1))
nplot(x, layout = l, edge.curvature = pi, vertex.size.range = c(.05,.1))
par(oldpar)
```

```{r edge-line-type, fig.width=6, fig.height=6, fig.cap="Changing the number of breaks in the edge (arc) and the type of line to be drawn."}
oldpar <- par(mfrow = c(2,2))
nplot(x, layout = l, edge.line.breaks=3)
nplot(x, layout = l, edge.line.lty = 2, edge.line.breaks=10)
nplot(x, layout = l, edge.line.lty = 3, edge.line.breaks=10)
nplot(x, layout = l, edge.line.lty = 4, edge.line.breaks=10)
par(oldpar)
```
