# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R CI 

on: [push, pull_request]

env:
  cntr: usccana/netplot:latest

jobs:
  build:
    runs-on: Ubuntu-latest
    strategy:
      matrix:
        include:
        - name: release
           cmd: R
        - name: dev
           cmd: RD

    steps:
      - uses: actions/checkout@v2

      - name: Container
        run: docker pull ${{ cntr }}

      - name: SessionInfo
        run: docker run --rm -i -v ${PWD}:/mnt -w /mnt ${{ cntr }} ${{ matrix.cmd }} -q -e 'sessionInfo()'

      - name: Build
        run: docker run --rm -i -v ${PWD}:/mnt -w /mnt ${{ cntr }} ${{ matrix.cmd }} CMD build --no-build-vignettes --no-manual .

      - name: Check
        run: docker run --rm -i -v ${PWD}:/mnt -w /mnt -e CI=true ${{ cntr }} ${{ matrix.cmd }} CMD check --no-vignettes --no-manual netplot_*.tar.gz

